# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    assignees:
      - "46ki75"
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    assignees:
      - "46ki75"
    labels:
      - "Rust"
      - "dependencies"
    groups:
      notionrs:
        patterns:
          - "notionrs"
          - "notionrs*"
          - "notion-to-jarkup"
      aws-sdk:
        patterns:
          - "aws-config"
          - "aws-sdk*"
      aws-lambda-runtime:
        patterns:
          - "lambda_http"
          - "lambda_runtime"
      serde:
        patterns:
          - "serde"
          - "serde*"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    target-branch: "develop"
    assignees:
      - "46ki75"
    labels:
      - "Terraform"
      - "dependencies"
