[package]
name = "cache-warmer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
dotenvy = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true }
scraper = "0.25.0"
